const COMMENTS_REQUEST_START = 'COMMENTS_REQUEST_START';
const COMMENTS_REQUEST_DONE = 'COMMENTS_REQUEST_DONE';
const COMMENTS_REQUEST_ERROR = 'COMMENTS_REQUEST_ERROR';

export {
    COMMENTS_REQUEST_START,
    COMMENTS_REQUEST_DONE,
    COMMENTS_REQUEST_ERROR,
};
