const POSTS_REQUEST_START = 'POST_REQUEST_START';
const POSTS_REQUEST_DONE = 'POST_REQUEST_DONE';
const POSTS_REQUEST_ERROR = 'POST_REQUEST_ERROR';

export {
    POSTS_REQUEST_START,
    POSTS_REQUEST_DONE,
    POSTS_REQUEST_ERROR,
};
